//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PraktikaActivity
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    public partial class Events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Events()
        {
            this.Activities = new HashSet<Activities>();
        }
        public string GetPhoto
        {
            get
            {
                string imagePath = Directory.GetCurrentDirectory() + @"\Images\" + Id + ".jpeg";
                if (File.Exists(imagePath))
                {
                    return imagePath;
                }
                else
                {
                    string[] extensions = { ".png", ".jpg", ".gif" };
                    foreach (var ext in extensions)
                    {
                        imagePath = Directory.GetCurrentDirectory() + @"\Images\" + Id + ext;
                        if (File.Exists(imagePath))
                        {
                            return imagePath;
                        }
                    }
                }
                // Если изображение не найдено ни в одном из форматов, можно вернуть значение по умолчанию или бросить исключение
                return string.Empty;
            }
        }
        public int Id { get; set; }
        public string EventName { get; set; }
        public System.DateTime StartDate { get; set; }
        public int Length { get; set; }
        public int CityID { get; set; }
        public Nullable<int> DirectionId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Activities> Activities { get; set; }
        public virtual Cities Cities { get; set; }
        public virtual Directions Directions { get; set; }
    }
}
